DROP DATABASE IF EXISTS DONKEYFOODDB;
CREATE DATABASE DONKEYFOODDB;
USE DONKEYFOODDB;

#TABLA PARA USUARIOS
CREATE TABLE USUARIOS(
CORREO VARCHAR (300),
NOMBRE VARCHAR (300),
CONTRASENA VARCHAR (300)
);
INSERT INTO USUARIOS VALUES("PEDRO@GMAIL","JUAN","A1");
INSERT INTO USUARIOS VALUES("A@GMAIL","A1","A1");

SELECT * FROM USUARIOS;

#TABLA PARA VENDEDORES
CREATE TABLE VENDEDORES(
CORREOV VARCHAR (300),
NOMBREV VARCHAR (300),
CONTRASENAV VARCHAR (300)
);

INSERT INTO VENDEDORES VALUES ("1","JUAN PEREZ","1JUAN");
INSERT INTO USUARIOS VALUES("A@GMAIL","A1","A1");
INSERT INTO VENDEDORES VALUES("A","A","A");
SELECT * FROM VENDEDORES;

#TABLA DE PRODUCTOS EN VENTA
CREATE TABLE PRODUCTOS(
IDPRODUCTO INT PRIMARY KEY,
CANTIDADPRODUCTO INT,
NOMBREPRODUCTO VARCHAR (300),
PRECIOPRODUCTO VARCHAR (30),
DESCRIPCIONPRODUCTO VARCHAR (300),
IMAGENPRODUCTO VARCHAR (9999),        #CAMBIAR UNA VEZ SE TENGA EL CODIGO PARA SUBIR ARCHIVOS TIPO PNG A LA BASE DE DATOS
DETALLESPRODUCTO VARCHAR (300)       #PARA GUARDAR LOS DETALLES DE LOS PRODUCTOS SE OCUPARA UN ARRAY DENTRO DE LOS JSP PARA QUE LOS PUEDA LEER SEPARADOS POR UNA ","
);

INSERT INTO PRODUCTOS VALUES ("1","2","COCA","20","COCACOLA DE 1 LITRO","HTTPS://THEFOODTECH.COM/WP-CONTENT/UPLOADS/2020/05/COCA-COLA.JPG","ES COCA");
INSERT INTO PRODUCTOS VALUES ("2","3","TORTA DE JAMON","50","TORTA DE JAMON","HTTPS://UPLOAD.WIKIMEDIA.ORG/WIKIPEDIA/COMMONS/THUMB/B/BB/TORTA_CUBANA.JPG/1200PX-TORTA_CUBANA.JPG","TORTA CON JAMON");
INSERT INTO PRODUCTOS VALUES ("3","3","DULCE","25","10 DULCES","HTTPS://S.CORNERSHOPAPP.COM/PRODUCT-IMAGES/1500044.JPG?VERSIONID=JFF.DRHBEWHVFBYSDICNIYZYOED0K4JL","10 DULCES ACIDULADITOS");
INSERT INTO PRODUCTOS VALUES ("4","3","PEPSI","20","PEPSI EN LATA","HTTPS://CDN.SHOPIFY.COM/S/FILES/1/0566/4391/1854/PRODUCTS/7501031311309_352C0CE2-9AB3-4721-B68C-F8F5BFA493D0.PNG?V=1626649481","200ML");
INSERT INTO PRODUCTOS VALUES ("5","3","HAMBURGUESA","60","HAMBURGUESA DE CARNE","HTTPS://UPLOAD.WIKIMEDIA.ORG/WIKIPEDIA/COMMONS/THUMB/6/62/NCI_VISUALS_FOOD_HAMBURGER.JPG/640PX-NCI_VISUALS_FOOD_HAMBURGER.JPG","LLEVA CARNE");
SELECT * FROM PRODUCTOS;

CREATE TABLE PEDIDOS(
IDUSUARIO INT,
IDVENDEDOR INT,
DETALLESPEDIDO VARCHAR (300),   #ACA SE ENVIARA EL ARREGLO DE LOS DETALLES DEL PEDIDO EN CASO DE QUE EL PRODUCTO TENGA DETALLES COMO CONDIMENTOS
FORMAPAGO VARCHAR (300),
FECHAPEDIDO VARCHAR (300),
FECHAFINPEDIDO VARCHAR (300)
);
INSERT INTO PEDIDOS VALUES (1,"1","DETALLE,XD","EFECTIVO","1/2/23","2/3/23");
SELECT * FROM PEDIDOS;

CREATE TABLE BOLSA(
CORREO VARCHAR (300),
OBJETOS VARCHAR (1000), #AQUI SE GURDARA EL ARRAY DE LOS OBJETOS PARA QUE LE LLEGUE EL MENSAJE A LA CAFETERIA DE LOS PRODUCTOS QUE SE QUIEREN 
DETALLES VARCHAR (1000) #ACA SE VA A GUARDAR EL ARRAY DE CADA UNO DE LOS DETALLES DE CADA PEDIDO
);

CREATE TABLE PED(

CORREO VARCHAR (300),
PRODUCTOS VARCHAR (300),
NOTA VARCHAR (300),
ESTADO VARCHAR (300)
);
SELECT  * FROM PED;